### ISSUE TITLE
Add feature to select path to Ashita

### ISSUE THREAD

**Issue by Mykezero** [Mykezero/Simulog#2]
Change how the program accesses Ashita by allowing them to select a path to the client, as opposed to dropping Simulog and its dependencies into the same directory as it. The current way the program works clutters up Ashita's folders.

**Comment by Mykezero** [comment]
This feature has now been added to the program.

**Comment by cym4567** [comment]
Hello, do you need a few days this script can use normally?

**Comment by cym4567** [comment]
Hello, do you need a few days this script can use normally?

**Comment by Mykezero** [comment]
I'm sorry, I don't understand your question.
